a
Getting album tracks for train_tracks.csv
Found 100 albums for z
Album tracks: 100Album tracks: 200Exausted album queries
Getting lastfm tracks for train_tracks.csv
Failed to fetch Spotify preview URL: 504 Server Error: Gateway Timeout for url: https://open.spotify.com/embed/track/1jMoqWkfjRDDZZ3ZLdcopE
Failed to fetch Spotify preview URL: 504 Server Error: Gateway Timeout for url: https://open.spotify.com/embed/track/3hzlF5hhliXmsxK8sBHfKJ
Failed to fetch Spotify preview URL: 504 Server Error: Gateway Timeout for url: https://open.spotify.com/embed/track/7AtcUQXvJnnwTrkUDYcYoV
Lastfm tracks: 100Failed to fetch Spotify preview URL: 504 Server Error: Gateway Timeout for url: https://open.spotify.com/embed/track/00K0B8nvfmTif7poYsk378
Lastfm tracks: 200Lastfm tracks: 300Failed to fetch Spotify preview URL: 504 Server Error: Gateway Timeout for url: https://open.spotify.com/embed/track/1Nb3mnnFcV2qz7z8Cv80Pf
Failed to fetch Spotify preview URL: 504 Server Error: Gateway Timeout for url: https://open.spotify.com/embed/track/3fNup3ZHQvP0sjed4BW5gm
Lastfm tracks: 400Failed to fetch Spotify preview URL: 504 Server Error: Gateway Timeout for url: https://open.spotify.com/embed/track/3JsA2sWDNR9oQogGAzqqtH
Traceback (most recent call last):
  File "/gpfs/scratch/jvaska/pzn/data/get_dataset.py", line 360, in <module>
    main()
  File "/gpfs/scratch/jvaska/pzn/data/get_dataset.py", line 328, in main
    get_lastfm_tracks(sp, n_tracks=200000, cluster_size=4) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/scratch/jvaska/pzn/data/get_dataset.py", line 180, in get_lastfm_tracks
    similar_tracks = track.get_similar(limit=cluster_size-1)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/scratch/jvaska/pzn/data/venv/lib/python3.12/site-packages/pylast/__init__.py", line 2169, in get_similar
    doc = self._request(self.ws_prefix + ".getSimilar", True, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/scratch/jvaska/pzn/data/venv/lib/python3.12/site-packages/pylast/__init__.py", line 1128, in _request
    return _Request(self.network, method_name, params).execute(cacheable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/scratch/jvaska/pzn/data/venv/lib/python3.12/site-packages/pylast/__init__.py", line 956, in execute
    response = self._download_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/scratch/jvaska/pzn/data/venv/lib/python3.12/site-packages/pylast/__init__.py", line 945, in _download_response
    self._check_response_for_errors(response_text)
  File "/gpfs/scratch/jvaska/pzn/data/venv/lib/python3.12/site-packages/pylast/__init__.py", line 974, in _check_response_for_errors
    raise WSError(self.network, status, details)
pylast.WSError: Track not found
